// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABDwVCHqL7rCVdX2s13U-7wJvQpH4EA_U',
    appId: '1:947433096148:web:4fdc71ab14643bf4ba4c41',
    messagingSenderId: '947433096148',
    projectId: 'travelapp-10036',
    authDomain: 'travelapp-10036.firebaseapp.com',
    storageBucket: 'travelapp-10036.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa23r8bS0gJ_kKx5ovEPgmYkrabMSRb0o',
    appId: '1:947433096148:android:374ca07ce562cae1ba4c41',
    messagingSenderId: '947433096148',
    projectId: 'travelapp-10036',
    storageBucket: 'travelapp-10036.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByrzqfNlUBKY_A8_PHA0IC1Ofsnfrnjxs',
    appId: '1:947433096148:ios:595a422e530164aeba4c41',
    messagingSenderId: '947433096148',
    projectId: 'travelapp-10036',
    storageBucket: 'travelapp-10036.firebasestorage.app',
    iosBundleId: 'com.example.projetoFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByrzqfNlUBKY_A8_PHA0IC1Ofsnfrnjxs',
    appId: '1:947433096148:ios:595a422e530164aeba4c41',
    messagingSenderId: '947433096148',
    projectId: 'travelapp-10036',
    storageBucket: 'travelapp-10036.firebasestorage.app',
    iosBundleId: 'com.example.projetoFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABDwVCHqL7rCVdX2s13U-7wJvQpH4EA_U',
    appId: '1:947433096148:web:f61aeaa00443cfd6ba4c41',
    messagingSenderId: '947433096148',
    projectId: 'travelapp-10036',
    authDomain: 'travelapp-10036.firebaseapp.com',
    storageBucket: 'travelapp-10036.firebasestorage.app',
  );

}